# Generated by Django 5.0.1 on 2026-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passphrase",
            field=models.CharField(default="Test", max_length=255),
            preserve_default=False,
        ),
    ]
