# Generated by Django 5.0.1 on 2026-09-10 20:32

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.avatar_upload_to,
                validators=[accounts.validators.validate_avatar],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="passphrase",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
