# Generated by Django 5.0.1 on 2026-04-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subrooms",
                to="chat.chatroom",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Message"),
                    ("group", "Group Chat"),
                    ("subgroup", "Sub Group"),
                ],
                default="direct",
                max_length=10,
            ),
        ),
    ]
