# Generated by Django 5.0.1 on 2026-09-10 20:32

import accounts.validators
import chat.models
import chat.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatroom_parent_alter_chatroom_room_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="room_avatars/",
                validators=[accounts.validators.validate_avatar],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=chat.models.message_attachment_upload_to,
                validators=[chat.validators.validate_attachment],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("voice", "Voice"),
                    ("file", "File"),
                    ("system", "App Notif"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "created_at", "is_deleted"],
                name="chat_messag_room_id_562776_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messageread",
            index=models.Index(
                fields=["user", "read_at"], name="chat_messag_user_id_337e77_idx"
            ),
        ),
    ]
