# Generated by Django 5.0.1 on 2026-09-10 20:54

import accounts.validators
import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chatroom_avatar_alter_message_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=chat.models.room_avatar_upload_to,
                validators=[accounts.validators.validate_avatar],
            ),
        ),
    ]
