# Generated by Django 5.0.1 on 2026-09-10 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_randomized_upload_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["parent", "is_active"], name="chat_chatro_parent__2b61b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(
                fields=["room", "last_read_at"], name="chat_roompa_room_id_bfb6cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomparticipant",
            index=models.Index(
                fields=["room", "is_typing", "typing_started_at"],
                name="chat_roompa_room_id_062f14_idx",
            ),
        ),
    ]
