# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_production_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConfiguration",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Paradise Chat", max_length=100),
                ),
                ("site_description", models.CharField(blank=True, max_length=255)),
                ("registration_enabled", models.BooleanField(default=True)),
                ("file_uploads_enabled", models.BooleanField(default=True)),
                ("moderation_enabled", models.BooleanField(default=False)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("max_message_length", models.PositiveIntegerField(default=5000)),
                ("max_attachment_size_mb", models.PositiveIntegerField(default=10)),
                ("primary_color", models.CharField(default="#0A2342", max_length=20)),
                ("accent_color", models.CharField(default="#2CA58D", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat configuration",
                "verbose_name_plural": "Chat configuration",
            },
        ),
    ]
